name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install neovim
        run: |
          wget https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
          tar -zxf nvim-linux64.tar.gz
          sudo ln -s $(pwd)/nvim-linux64/bin/nvim /usr/local/bin

      - name: Create file with year and week day to cache for a week
        run: |
          date +%Y-%U > current-year-week
          cat current-year-week

      - name: Try getting treesitter parser cache of this week
        id: treesitter-cache
        uses: actions/cache@v3
        with:
          path: nvim-treesitter
          key: treesitter-hash-${{ hashFiles('current-year-week') }}


      - name: Install treesitter parser
        if: ${{ steps.treesitter-cache.outputs.cache-hit != 'true' }}
        run: |
          git clone https://github.com/nvim-treesitter/nvim-treesitter
          nvim --headless --noplugin -u scripts/minimal_init.lua +"TSInstallSync all" -c "q"

      - name: Run Script for tests
        run: ./scripts/run_tests.sh
